model:
  type: kl
  kl_weight: 0.000001
  pixelloss_weight: 1.0
  perceptual_weight: 1.0
  params:
    embed_dim: 3
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []